### ISSUE TITLE
Makefile.PL is missing from repository?

### ISSUE THREAD

**Issue by manwar** [saiftynet/GUIDeFATE#7]
Hi @saiftynet 

Can you please add the Makefile.PL script to GitHub repository?
Or if you want I can create a PR for the same?

Best Regards,
Mohammad S Anwar

**Comment by saiftynet** [comment]
Was not going to put it there at all ...it is in the tar.gz...otherwise it just pollutes the directory which is currently in constant flux anyway.  Once stable, only rarely changing, and once all the tests are done, I will clean the directory structure.  Currently this is very much an alpha, and though it is on CPAN it will very likely fail to install on many systems.
